### PR TITLE
fix: support dark mode for 'X' and 'disabled-input' in shadow modal

### LINKED ISSUE #426: Xs and disabled input on shadow modal looks off in dark mode
Screen Shot 2023-05-12 at 7 03 19 PM

### PR DESCRIPTION
**Pull request by Pranav2612000**
Fixed #426

### CODE REVIEW

File: packages/core/src/components/Shadows/EditShadowModal.tsx [hunk 1]
```diff
@@ -357,19 +357,26 @@ export function EditShadowModal({
                 }}
               >
                 {newInitialValues?.map((_arg: ShadowValue, index: number) => {
+                  const opacity = index === shadowIndex ? '1' : '0.4';
```
Comment (Pranav2612000) [inline packages/core/src/components/Shadows/EditShadowModal.tsx:360]: Using an opacity based approach because it's the same one used by ChakraUI - It adds an `opacity: 0.4` for disabled inputs.

**Comment by Pranav2612000** [comment]
Kapture 2023-05-15 at 08 07 27

**Comment by alexdanilowicz** [comment]
Looks great!
